#!/bin/bash
echo build -o domainfinder ... 
go build -o ./domainify/domainfinder

echo build -o synonyms ... 
go build -o ./synonyms/synonyms

echo build -o available ... 
go build -o ./available/available

echo build -o sprinkle ... 
go build -o ./sprinkle/sprinkle

echo build -o coolify ... 
go build -o ./coolify/coolify

echo build -o theasurus ... 
go build -o ./theasurus/theasurus
